Repository GarlicoinOrg/Garlicoin, pull requests merged in 2018-02, with the labels that each got.

#39 Testnet hard fork: Allium PoW algorithm
  Makefile.am
  asdf
  configure.ac
  src/Makefile.am
  src/Makefile.test.include
  src/chain.h
  src/chainparams.cpp
  src/chainparams.h
  src/crypto/Lyra2RE/Lyra2.c
  src/crypto/Lyra2RE/Lyra2.h
  src/crypto/Lyra2RE/Lyra2RE.c
  src/crypto/Lyra2RE/Lyra2RE.h
  src/crypto/Lyra2RE/Sponge.c
  src/crypto/Lyra2RE/Sponge.h
  src/crypto/Lyra2RE/blake.c
  src/crypto/Lyra2RE/bmw.c
  src/crypto/Lyra2RE/cubehash.c
  src/crypto/Lyra2RE/groestl.c
  src/crypto/Lyra2RE/keccak.c
  src/crypto/Lyra2RE/skein.c
  src/crypto/Lyra2RE/sph_blake.h
  src/crypto/Lyra2RE/sph_bmw.h
  src/crypto/Lyra2RE/sph_cubehash.h
  src/crypto/Lyra2RE/sph_groestl.h
  src/crypto/Lyra2RE/sph_keccak.h
  src/crypto/Lyra2RE/sph_skein.h
  src/crypto/Lyra2RE/sph_types.h
  src/crypto/allium/allium.c
  src/crypto/allium/allium.h
  src/primitives/block.cpp
  src/primitives/block.h
  src/rpc/mining.cpp
  src/test/blockencodings_tests.cpp
  src/test/crypto_tests.cpp
  src/test/test_bitcoin.cpp
  src/validation.cpp
  src/validation.h
Labels: consensus, hard fork, review needed, validation

#41 Allium: Add main net fork at 58671
  src/chainparams.h
Labels: consensus, hard fork, review needed, validation

#46 Update web link to garlicoin.io
  .github/ISSUE_TEMPLATE.md
  configure.ac
  contrib/README.md
  doc/README.md
  doc/gitian-building.md
  doc/litecoin-release-notes/release-notes-0.13.2.md
  doc/man/garlicoin-cli.1
  doc/man/garlicoin-qt.1
  doc/man/garlicoin-tx.1
  doc/man/garlicoind.1
  doc/release-notes-litecoin.md
  doc/release-process.md
  src/init.cpp
  src/qt/guiconstants.h
Labels: bug, ui

#48 Add DNS Seed dnsseed.garli.co.in
  src/chainparams.cpp
Labels: enhancement, networking, review needed

#47 [QT] Fixed icns file not aligning with the png/ico files
  src/qt/res/icons/bitcoin.icns
Labels: review needed, ui

#43 Create install_db4.sh
  contrib/install_db4.sh
Labels: enhancement, review needed

#31 Fixed incorrect references to external resources
  .github/ISSUE_TEMPLATE.md
Labels: documentation, review needed
